BioIO links and dependency versions (#36)
Small saga of bug reports.

1. Some dependency change lead to
    > FAILED tests/images/test_bioio_server.py::test_read_float_5d_zarr_image_with_dask - TypeError: Can't instantiate abstract class BioImage with abstract methods scale, standard_metadata, time_interval

    across many tests. As we were massively out of date from bioio
    (1.1.0 <<<< 3.0.0), I thought it would be more expedient to simply
    update, rather than fix our old dependencies.
2. Some versions of the bioio zarr package don't have the zarr writer,
    leading to 
    > ERROR tests/images/test_bioio_server.py - AttributeError: module 'bioio.writers' has no attribute 'OmeZarrWriter'. Did you mean: 'OmeTiffWriter'?

    Updating to bioio-ome-zarr ~= 2.3.0 fixes this.
3. This requires a bump to python 3.11
4. The zarr writer API has changed, for example
    > E   TypeError: OMEZarrWriter.__init__() missing 2 required positional arguments: 'shape' and 'dtype'

    In particular, this required changing how channel names
    and pixel sizes are specified.
    
5. A recent update in zarr removed some abstract methods:
    > FAILED tests/images/test_bioio_server.py::test_read_uint8_3channels_image - TypeError: Can't instantiate abstract class ZarrTiffStore with abstract methods set_partial_values, supports_partial_writes

    Very recent tifffile has been updated to reflect this change:
    https://github.com/cgohlke/tifffile/commit/0512b192e1225fc439616738291817fc81e15af6
    However, this means that it is incompatible with old versions of
    zarr (<3.1.3). See https://github.com/cgohlke/tifffile/issues/310